### ISSUE TITLE
Unresolved reference: BlurDialog

### ISSUE THREAD

**Issue by AlaaZarifa** [x3rocode/xblur-compose#1]
I don't know what's the issue, but my project is unable to download the library somehow.

I have added the dependency in my app `build.gradle` file just like any library.

```
dependencies {
    implementation 'com.github.x3rocode:xblur-compose:1.0.1'
}
```

Error
-

<img width="679" alt="image" src="https://user-images.githubusercontent.com/18426012/224072560-3a240ccd-8303-42ea-878f-a1117fdcaff6.png">

**Comment by AlaaZarifa** [comment]
Nevermind, that's the reason 
 **`requires API level 33 (current min is 24): BlurDialog`**

**Comment by 23-59** [comment]
> Nevermind, that's the reason **`requires API level 33 (current min is 24): BlurDialog`**

are you sure? cause I changed min SDK to 33 and I can't still use the library
